# Generated by Django 4.0.4 on 2022-05-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_atividade_arquiv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
